module.exports = {
  Lessons: [{
    type: 'category',
    label: 'Lessons',
    link: {
      type: 'generated-index',
      title: 'Lessons',
      slug: '/Lessons',
    },
    items: [{
      type: "autogenerated",
      dirName: "Lessons"
    }]
  }],
  TDs: [{
    type: 'category',
    label: 'TDs',
    link: {
      type: 'generated-index',
      title: 'TDs',
      slug: '/TDs',
    },
    items: [{
      type: "autogenerated",
      dirName: "TDs"
    }]
  }],
}
