module.exports = {
  Lessons: [{
    type: 'category',
    label: 'Lessons',
    link: {
      type: 'generated-index',
      title: 'Lessons',
      slug: '/Lessons',
    },
    items: [{
      type: "autogenerated",
      dirName: "Lessons/S1"
    }]
  }],
  TDs: [{
    type: 'category',
    label: 'TDs',
    link: {
      type: 'generated-index',
      title: 'TDs',
      slug: '/TDs',
    },
    items: [{
      type: "autogenerated",
      dirName: "TDs/S1"
    }]
  }],
  Annexes: [{
    type: 'category',
    label: 'Annexes',
    link: {
      type: 'generated-index',
      title: 'Annexes',
      slug: '/Annexes',
    },
    items: [{
      type: "autogenerated",
      dirName: "Annexes"
    }]
  }],
}
