module.exports = {
  Lessons: [{
    type: 'category',
    label: 'Cours',
    link: {
      type: 'generated-index',
      title: 'Cours',
      slug: '/Lessons',
    },
    items: [{
      type: "autogenerated",
      dirName: "Lessons"
    }]
  }],
  TDs: [{
    type: 'category',
    label: 'TDs',
    link: {
      type: 'generated-index',
      title: 'TDs',
      slug: '/TDs',
    },
    items: [{
      type: "autogenerated",
      dirName: "TDs"
    }]
  }],
  Annexes: [{
    type: 'category',
    label: 'Annexes',
    link: {
      type: 'generated-index',
      title: 'Annexes',
      slug: '/Annexes',
    },
    items: [{
      type: "autogenerated",
      dirName: "Annexes"
    }]
  }],
  Workshop: [{
    type: 'category',
    label: 'Workshop',
    link: {
      type: 'generated-index',
      title: 'Workshop',
      slug: '/Workshop',
    },
    items: [{
      type: "autogenerated",
      dirName: "Workshop"
    }]
  }],
}
